#!/usr/bin/env bash
# Use a while loop to display "Best School" 10 times with a special case for the 9th iteration.

count=0
while [ "$count" -lt 10 ]
	do
	if [ "$count" -eq 8 ]
		then
			echo "Best School"
			echo "Hi"
	else
		echo "Best School"
	fi

	(( count++ ))
	done
