#!/usr/bin/env bash
# Use a while loop to loop from 1 - 10
# Displays bad luck from the 4th loop iteration.
# Displays good luck from the 8th loop iteration.
# Displays School for the other iteration.

count=0
while [ $count -lt 10 ]
	do
		if [ $count -eq  3 ]
		then
			echo "bad luck"
		elif [ $count -eq 7 ]
		then
			echo "good luck"
		else
			echo "Best School"
		fi
		(( count++ ))
	done
