#!/usr/bin/env bash
# display 4 and then bad luck from China for the 4th loop iteration.
# display 9 and the bad luck from Japan for the 9th loop iteration.
# display 17 and then bad luck from Italy for the 17th loop iteration.

count=1

while [ $count -le 20 ]
	do
		echo  "$count"
		case $count in
			"4") echo "bad luck from China";;
			"9") echo "bad luck from Japan";;
			"17") echo "bad luck from Italy";;
		esac
		(( count++ ))
	done
